CAPITAL_MARKET_ASSUMPTIONS = {
    "br_b3_corporate_bond_di_aaa_index": "Renda Fixa Pós-Fixado (Debêntures AAA DI)",
    "br_b3_corporate_bond_di_ultra_quality_index": "Renda Fixa Pós-Fixado (Debêntures Ultra Quality DI)",
    "br_b3_corporate_bond_incentivized_ipca_ultra_quality_index": "Renda Fixa IPCA (Debêntures Incentivadas IPCA Ultra Quality)",
    "br_b3_corporate_bond_incentivized_ipca_aaa_index": "Renda Fixa IPCA (Debêntures Incentivadas IPCA AAA)",
    "br_cdi_index": "Caixa e Equivalentes (CDI)",
    "br_ibovespa": "Bolsa Brasileira (Ibovespa)",
    "IVVB11": "Bolsa Americana (com variação cambial - IVVB11)",
    "us_sp500": "Bolsa Americana (sem variação cambial)",
    "br_ifix": "Fundos Imobiliários (IFIX)",
    "anbima_ihfa": "Fundos Multimercado (IHFA)",
    "br_mlcx": "Large Caps Brasileiros (MLCX)",
    "br_smll": "Small Caps Brasileiros (SMLL)",
    "gold_100oz_futures": "Ouro (sem variação cambial)",
    # "bitcoin_usd": "Bitcoin",
    "anbima_ima_b5": "Títulos Públicos IPCA Curto (IMA-B 5)",
    "anbima_ima_b5+": "Títulos Públicos IPCA Longo (IMA-B 5+)",
    "anbima_irf_m1": "Títulos Públicos Pré-Fixados Curto (IRF-M 1)",
    "anbima_irf_m1+": "Títulos Públicos Pré-Fixados Longo (IRF-M 1+)",
}