CTA_DASHBOARD = {
    "cta_holdings_evolution": {
        "chart_config": {
            "instruments": [
                {"id": "us_3month_sofr_futures", "name": "3M SOFR Futures"},
                {"id": "canada_corra_3m_futures", "name": "3M Corra Futures"},
                {"id": "canada_govt_10y_futures", "name": "10Y Government Futures"},
                {"id": "canada_govt_2y_futures", "name": "2Y Government Futures"},
                {"id": "canada_govt_5y_futures", "name": "5Y Government Futures"},
                {"id": "canola_futures", "name": "Canola Futures"},
                {"id": "cattle_feeder_futures", "name": "Cattle Feeder Futures"},
                {"id": "cocoa_futures", "name": "Cocoa Futures"},
                {"id": "coffee_c_futures", "name": "Coffee Futures"},
                {"id": "copper_futures", "name": "Copper Futures"},
                {"id": "corn_futures", "name": "Corn Futures"},
                {"id": "cotton_n2_futures", "name": "Cotton Futures"},
                {"id": "gasoline_rbob_futures", "name": "Gasoline Futures"},
                {"id": "gold_100oz_futures", "name": "Gold Futures"},
                {"id": "wheat_kc_hrw_futures", "name": "KC HRW Wheat Futures"},
                {"id": "lean_hogs_futures", "name": "Lean Hogs Futures"},
                {"id": "live_cattle_futures", "name": "Live Cattle Futures"},
                {"id": "natural_gas_futures", "name": "Natural Gas Futures"},
                {"id": "ulsd_ny_harbor_futures", "name": "ULSD NY Harbor Futures"},
                {"id": "palladium_futures", "name": "Palladium Futures"},
                {"id": "platinum_futures", "name": "Platinum Futures"},
                {"id": "silver_futures", "name": "Silver Futures"},
                {"id": "soybean_futures", "name": "Soybean Futures"},
                {"id": "soybean_meal_futures", "name": "Soybean Meal Futures"},
                {"id": "soybean_oil_futures", "name": "Soybean Oil Futures"},
                {"id": "sugar_futures", "name": "Sugar Futures"},
                {"id": "us_ultra_treasury_note_10y_futures", "name": "10Y US Treasury Futures"},
                {"id": "us_treasury_note_2y_futures", "name": "2Y US Treasury Futures"},
                {"id": "us_treasury_bond_futures", "name": "US Treasury Bond Futures"},
                {"id": "us_treasury_ultra_bond_futures", "name": "US Treasury Ultra Bond Futures"},
                {"id": "wheat_futures", "name": "Wheat Futures"},
                {"id": "crude_oil_wti_futures", "name": "Crude Oil WTI Futures"}
            ],
            "chart_type": "area",
            "title": "Holdings",
            "y_axis_title": "Holdings (%)",
        },
        "width": 12,
        "group": "Holdings",
        "context": "CTA"
    },
}