CTA_DASHBOARD = {
    "aud_usd_futures": "AUD/USD",
    "australia_asx200_futures": "Australia ASX200",
    "australia_govt_bond_10y_futures": "Australia Govt Bond 10Y",
    "australia_govt_bond_3y_futures": "Australia Govt Bond 3Y",
    "cad_usd_futures": "CAD/USD",
    "canada_corra_3m_futures": "3M Corra",
    "canada_govt_10y_futures": "Canada Govt Bond 10Y",
    "canada_govt_2y_futures": "Canada Govt Bond 2Y",
    "canada_govt_5y_futures": "Canada Govt Bond 5Y",
    "canada_tsx60_futures": "Canada TSX60",
    "canola_futures": "Canola",
    "cattle_feeder_futures": "Cattle Feeder",
    "chf_usd_futures": "CHF/USD",
    "cocoa_futures": "Cocoa",
    "coffee_c_futures": "Coffee",
    "copper_futures": "Copper",
    "corn_futures": "Corn",
    "cotton_n2_futures": "Cotton N2",
    "crude_oil_brent_futures": "Crude Oil Brent",
    "crude_oil_wti_futures": "Crude Oil WTI",
    "eur_usd_futures": "EUR/USD",
    "euro_bobl_5y_futures": "Germany Euro Bobl 5Y",
    "euro_btp_futures": "Germany Euro BTP",
    "euro_bund_10y_futures": "Germany Euro Bund 10Y",
    "euro_buxl_30y_futures": "Germany Euro Buxl 30Y",
    "euro_stoxx50_futures": "Euro Stoxx 50",
    "france_cac40_futures": "France CAC40",
    "france_govt_bond_futures": "France Govt Bond",
    "gasoil_futures": "Gasoil",
    "gasoline_rbob_futures": "Gasoline RBOB",
    "gbp_usd_futures": "GBP/USD",
    "germany_dax_futures": "Germany DAX",
    "gold_100oz_futures": "Gold 100oz",
    "italy_ftse_mib_futures": "Italy FTSE MIB",
    "japan_govt_bond_10y_futures": "Japan Govt Bond 10Y",
    "japan_topix_futures": "Japan TOPIX",
    "jpy_usd_futures": "JPY/USD",
    "lean_hogs_futures": "Lean Hogs",
    "live_cattle_futures": "Live Cattle",
    "lme_aluminum_futures": "LME Aluminum",
    "lme_copper_futures": "LME Copper",
    "long_gilt_futures": "Long Gilt",
    "msci_emerging_markets_futures": "MSCI Emerging Markets",
    "natural_gas_futures": "Natural Gas",
    "nzd_usd_futures": "NZD/USD",
    "palladium_futures": "Palladium",
    "platinum_futures": "Platinum",
    "silver_futures": "Silver",
    "soybean_futures": "Soybean",
    "soybean_meal_futures": "Soybean Meal",
    "soybean_oil_futures": "Soybean Oil",
    "spain_ibex35_futures": "Spain IBEX35",
    "sugar_futures": "Sugar",
    "sweden_omxs30_futures": "Sweden OMXS30",
    "uk_ftse100_futures": "UK FTSE100",
    "ulsd_ny_harbor_futures": "ULSD NY Harbor",
    "us_3month_sofr_futures": "3M SOFR",
    "us_mini_russell2000_futures": "US Mini Russell 2000",
    "us_mini_sp500_futures": "US Mini S&P 500",
    "us_treasury_bond_futures": "US Treasury Bond",
    "us_treasury_note_10y_futures": "US Treasury Note 10Y",
    "us_treasury_note_2y_futures": "US Treasury Note 2Y",
    "us_treasury_note_5y_futures": "US Treasury Note 5Y",
    "us_treasury_ultra_bond_futures": "Ultra US Treasury Bond",
    "us_ultra_treasury_note_10y_futures": "Ultra 10Y US Treasury Note",
    "wheat_futures": "Wheat",
    "wheat_kc_hrw_futures": "KC HRW Wheat",
}