EXCLUIR_FUNDOS = {"LCM BAND FIRF"}

DISTRIBUIDORES = ["XP", "BTG", "Outros"]

DISTRIBUIDOR_NOMES = {
    "XP": "XP Investimentos",
    "BTG": "BTG Digital",
    "Outros": "Outros distribuidores",
}

OPERACAO_APLICACAO = "APLICAÇÃO"
OPERACAO_RESGATE = "RESGATE"
OPERACOES = [OPERACAO_APLICACAO, OPERACAO_RESGATE]

TIPO_MOVIMENTO_COME_COTAS = "RESGATE COME COTAS"

COLUNA_FINANCEIRO = "Financeiro previsto (R$)"
COLUNA_STATUS = "Status"
COLUNA_TIPO_MOVIMENTO = "Tipo movimento"
COLUNA_FUNDO = "Nome da classe/subclasse"
COLUNA_CLIENTE = "Cliente"
COLUNA_OPERACAO = "Operação"
COLUNA_BOLETA_ID = "Boleta ID"

REQUIRED_COLUMNS = [
    COLUNA_STATUS,
    COLUNA_TIPO_MOVIMENTO,
    COLUNA_FUNDO,
    COLUNA_CLIENTE,
    COLUNA_OPERACAO,
    COLUNA_FINANCEIRO,
    COLUNA_BOLETA_ID,
]
