FACTOR_OPTIONS = {
    'br_cdi_index': 'CDI',
    'br_ibovespa': 'Ibovespa',
    'us_sp500': 'S&P 500',
    'br_bmf_di_jan27_futures': 'DI Jan 27',
    'br_bmf_di_jan28_futures': 'DI Jan 28',
    'br_bmf_di_jan29_futures': 'DI Jan 29',
    'br_bmf_di_jan30_futures': 'DI Jan 30',
    'br_bmf_di_jan31_futures': 'DI Jan 31',
    'anbima_ima_b': 'IMA B',
    'anbima_ima_b5': 'IMA B5',
    'anbima_ima_b5+': 'IMA B5+',
    'br_bmf_us_treasury_10y_futures': '10y US',
    'brl_usd': 'BRL/USD',
    'gold': 'Gold',
    'crude_oil_wti_futures': 'Crude Oil WTI',
    'bitcoin_usd': 'Bitcoin',
    'china_kweb': 'China KWEB',
    'us_nasdaq100': 'Nasdaq 100',
}

FACTOR_OPTIONS_SELECTED = {
    'br_cdi_index': 'CDI',
    'br_ibovespa': 'Ibovespa',
    'us_sp500': 'S&P 500',
    'br_bmf_di_jan29_futures': 'DI Jan 29',
    'br_bmf_di_jan33_futures': 'DI Jan 33',
    'br_bmf_us_treasury_10y_futures': '10y US',
    'br_bmf_usd_futures': 'BRL/USD',
    'gold_100oz_futures': 'Gold',
    'crude_oil_wti_futures': 'Crude Oil WTI',
}