FACTOR_OPTIONS = {
    'br_cdi_index': 'CDI',
    'br_bmf_ibovespa_futures': 'Ibovespa',
    'br_bmf_sp500_futures': 'S&P 500',
    'br_bmf_di_jan27_futures': 'DI Jan 27',
    'br_bmf_di_jan28_futures': 'DI Jan 28',
    'br_bmf_di_jan29_futures': 'DI Jan 29',
    'br_bmf_di_jan30_futures': 'DI Jan 30',
    'br_bmf_di_jan31_futures': 'DI Jan 31',
    'br_bmf_di_jan32_futures': 'DI Jan 32',
    'br_bmf_di_jan33_futures': 'DI Jan 33',
    'anbima_ima_b': 'IMA B',
    'anbima_ima_b5': 'IMA B5 (Curto)',
    'anbima_ima_b5+': 'IMA B5+ (Longo)',
    'anbima_ima_geral': 'IMA Geral',
    'anbima_irf_m': 'IRF M',
    'anbima_irf_m1': 'IRF M1 (Curto)',
    'anbima_irf_m1+': 'IRF M1+ (Longo)',
    'br_bmf_us_treasury_10y_futures': '10y US',
    'br_bmf_usd_futures': 'BRL/USD',
    'crude_oil_wti_futures': 'Crude Oil WTI',
    'bitcoin_usd': 'Bitcoin',
    'china_kweb': 'China KWEB',
    'us_nasdaq100': 'Nasdaq 100',
    'gold_100oz_futures': 'Gold',
}

FACTOR_OPTIONS_SELECTED = {
    'br_cdi_index': 'CDI',
    'br_bmf_ibovespa_futures': 'Ibovespa',
    'br_bmf_sp500_futures': 'S&P 500',
    'br_bmf_di_jan29_futures': 'DI Jan 29',
    'br_bmf_di_jan33_futures': 'DI Jan 33',
    'br_bmf_us_treasury_10y_futures': '10y US',
    'br_bmf_usd_futures': 'BRL/USD',
    'gold_100oz_futures': 'Gold',
    'crude_oil_wti_futures': 'Crude Oil WTI',
}