[theme]
base = "light"
primaryColor = "#2C74B3"
backgroundColor = "#f2f2f2"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#262730"
font = "Roboto"
showSidebarBorder = true

[theme.sidebar]
backgroundColor = "#e0ecfc"
secondaryBackgroundColor = "#FFFFFF"

[server]
enableCORS = true
enableXsrfProtection = true

[global]
showWarningOnDirectExecution = false
developmentMode = false

[browser]
gatherUsageStats = false 