[theme]
base = "light"
primaryColor = "#0d2340"
backgroundColor = "#f2f2f2"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#192626"
font = "Roboto"
showSidebarBorder = true
dataframeBorderColor = "#e8e4dc"

[theme.sidebar]
backgroundColor = "#e0ecfc"
secondaryBackgroundColor = "#FFFFFF"

[server]
enableCORS = true
enableXsrfProtection = true

[global]
showWarningOnDirectExecution = false
developmentMode = false

[browser]
gatherUsageStats = false 